### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store_stripe_checkout#1]
Hi,

I get the following error installing in a new v8.5.1 site:

Concrete\Package\CommunityStoreStripeCheckout\Controller::on_start(): Failed opening required '/home/independantjewel/dev.independantjewellery.com/packages/community_store_stripe_checkout/vendor/autoload.php' (include_path='/home/independantjewel/dev.independantjewellery.com/concrete/vendor:.:/opt/alt/php73/usr/share/pear')

Stack frames (1)
0 Whoops\Exception\ErrorException 
/home/independantjewel/dev.independantjewellery.com/packages/community_store_stripe_checkout/controller.php19

Thanks
Dave

**Comment by Mesuva** [comment]
Are you using the release zip or just a copy of the master?

Looks like you haven't got the vendor folder in place.

**Comment by madesimplemedia** [comment]
I click "Clone or download" and then the zip, so maybe I am using the master? 
How do I download a release zip?

**Comment by Mesuva** [comment]
There should be a releases tab towards the top.

**Comment by madesimplemedia** [comment]
Working great now, thanks as always!
