### ISSUE TITLE
Stripe payment method doesn't show on checkout form

### ISSUE THREAD

**Issue by QuentindevePro** [concrete5-community-store/community_store_stripe_checkout#11]
I wanted to try this package on my Concrete 9 installation, but even with the Stripe payment method enabled the method didn't show in the checkout form. Checked my logs and got:
```
/home/dev3es/domains/c5store2.dev3.exterieurstock.fr/public_html/c5store/vendor/doctrine/orm/lib/Doctrine/ORM/Exception/MissingIdentifierField.php:13 The identifier oID is missing for a query of Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order (0)
```

After some checks the issue is on the createSession() method, because ``Session::get("orderID")`` is not defined in the session.

EDIT: Even the ``Invoice`` payment method doesn't show up.

**Comment by Mesuva** [comment]
It's still working for me - I get the checkout button, and pressing that takes me to Stripe's Checkout page.

What version of Community Store are you running, and have you made any overrides of the checkout single page?

**Comment by QuentindevePro** [comment]
Well, I uninstalled and reinstalled the package 2 times and it fixed the issue, I was on CS v.2.6.6-alpha2

**Comment by Mesuva** [comment]
Good to hear.
I should add, it's best not to use the master branch on any production sites - use the last release.
