### ISSUE TITLE
Unrecognized request URL

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store_stripe_checkout#2]
Hi

I am getting this error when trying to complete checkout, please see attached.

Stripe account is validated.  I have added the API keys and webhook.

I can see the error in Stripe too, here is the response body:

```
{
  "error": {
    "message": "Unrecognized request URL (POST: /v1/sessions). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}
```

Not sure what else I can check?

![stripe-unrecognised-url](https://user-images.githubusercontent.com/10834004/60168567-fe915180-97fc-11e9-84f6-e129d86d0dcf.jpg)

**Comment by Mesuva** [comment]
My understanding is that the URL it should be trying to call is /v1/checkout/sessions
but it's calling /v1/sessions here, which is odd.

Do you have the older Stripe payment add-on installed/enabled?

**Comment by madesimplemedia** [comment]
Yes, I seemed to need it to get the new one working.  Maybe because the site was upgraded.

**Comment by Mesuva** [comment]
You shouldn't need it at all.

Did you install just the master, or did you install the release from https://github.com/concrete5-community-store/community_store_stripe_checkout/releases ?

I'm wondering if you are missing the vendor directory, which is only present in the release

**Comment by madesimplemedia** [comment]
Definitely got the vendor directory, I think I installed the release in the end.

**Comment by Mesuva** [comment]
I'm wondering if the two Stripe vendor libraries are conflicting...
What happens when you uninstall the original Stripe add-on?

**Comment by madesimplemedia** [comment]
Awesome it works!  Doesn't like having old and new Stripe installed, but obviously that's not an issue as you wouldn't use the old one with the new one.  Thanks!

**Comment by Mesuva** [comment]
Now that it's been discovered I should probably add a note about that.
I thought they could be used together, but maybe it comes down to what order they are installed

**Comment by madesimplemedia** [comment]
Seems so in this case anyway
