### ISSUE TITLE
Integrity Constraint Violation installing 

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store_stripe_checkout#4]
Hi,

I have uninstalled the old Stripe payment addon, but get the following when installing the new addon:

`An exception occurred while executing 'ALTER TABLE CommunityStoreOrderItemOptions ADD CONSTRAINT FK_61F5DBA5550DB923 FOREIGN KEY (oiID) REFERENCES CommunityStoreOrderItems (oiID) ON DELETE CASCADE': SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`easyprint_dev`.`#sql-7aef_175dc4`, CONSTRAINT `FK_61F5DBA5550DB923` FOREIGN KEY (`oiID`) REFERENCES `CommunityStoreOrderItems` (`oiID`) ON DELETE CASCADE)`

**Comment by madesimplemedia** [comment]
![image](https://user-images.githubusercontent.com/10834004/61628564-8cd0ea00-ac7a-11e9-8d8d-6285351e5047.png)

**Comment by Mesuva** [comment]
This isn't an issue with the Stripe add-on as such, it's only because it's triggering a refresh of the database and this is this catching some data issue. Have you potentially at some point deleted some order records, without also deleting the order line items?

**Comment by madesimplemedia** [comment]
Thanks for getting back to me.  I guess that's possible, is there a way I can edit the DB to get it back to working?

**Comment by Mesuva** [comment]
Sure, something like PhpMyAdmin would get you into there, if you are using cPanel then that's going to be available. If you have your own custom hosting without any DB tools installed, I'm a fan of https://www.adminer.org/ - it's bare boned, but can do pretty much all the same things, and it's a single file to drop into your site's directory.

**Comment by madesimplemedia** [comment]
I have PHPMyAdmin.

In CommunityStoreOrderItems I have two row with oID = 4.  In CommunityStoreOrders, I only have one with oID = 4.  Do I need to delete one of the CommunityStoreOrderItems with oID = 4?

**Comment by Mesuva** [comment]
Well that sounds like you don't need to clean anything up.

Have you tried the trick of going to /index.php/dashboard/system/environment/entities and hitting the red Refresh Entities button?

**Comment by madesimplemedia** [comment]
Yeah that didn't seem to help.

I just uninstalled and installed 2.1.7 and it's working fine now.
