### ISSUE TITLE
Class 'Stripe\Stripe' not found

### ISSUE THREAD

**Issue by matttydubs** [concrete5-community-store/community_store_stripe_checkout#8]
Upon selecting the payment method on checkout, the console shows a 500 error from /checkout/stripecheckoutcreatesession?... which, when visited shows a Class 'Stripe\Stripe' not found error on line 206

/packages/community_store_stripe_checkout/src/CommunityStore/Payment/Methods/CommunityStoreStripeCheckout/CommunityStoreStripeCheckoutPaymentMethod.php:206

**Comment by Mesuva** [comment]
Did you install a release copy of the package?

**Comment by matttydubs** [comment]
Ah... No, I just downloaded the master from the root page. All better now, thanks!
