### ISSUE TITLE
Adjustable item integration

### ISSUE THREAD

**Issue by Samurai016** [concrete5-community-store/community_store_stripe_checkout#9]
Could be possible for this packaget to implement the new Stripe feature for change the item quantities directly inside Stripe as explained [here](https://stripe.com/docs/payments/checkout/adjustable-quantity)?

**Comment by Mesuva** [comment]
I don't think that will be possible. If a customer can change the quantity in Stripe checkout, that changes the order's details and pricing, and that's not going to then match with the order saved in Community Store.  Different quantities could also impact things like shipping prices, hence why the quantities need to be adjusted and known on the Community Store side of things before sending the customer to the payment gateway.

**Comment by Samurai016** [comment]
Oh right, I hadn't thought about the side effects it would have on shipping costs, taxes, etc.
It is actually not possible to implement this in an ecommerce that relies on Stripe for payments.
Thank you so much for the timely reply!

**Comment by Mesuva** [comment]
I even think it's a challenge even for simpler integrations, when things like stock levels are wanting to be controlled.
I have this add-on in the marketplace, which is just a simpler block to trigger sending someone to Stripe Checkout. 
https://www.concrete5.org/marketplace/addons/payments-with-stripe/

But even this has maximum cart quantities and stock level that can be restricted, and if if this option was enabled in the checkout it would override any previous restrictions set at the block level.  
(I might still add it as a feature if requested, just pointing out further challenges!)

**Comment by Samurai016** [comment]
Thank you very much but I think the problem is in the beginning, changing the quantities outside the marketplace means of course no checks on shipping costs, taxes.
Even if you can restrict the max quantity to fit the stock levels you have no control on the others parameters.
Maybe in some small use cases where the shipping costs and the taxes are free or fixed regardless of the items quantity, this feature could be implemented but it means you have to check these conditions before creating the Stripe session.
